version: "3.9"

services:
  app:
    image: amitavrchy/fahadpervej-mditems-app:latest
    container_name: fahadpervej-mditems-app
    restart: unless-stopped
    ports:
      - "5056:5056"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge