# Name this (It can be anything)
name: CI/CD For test and deployment

on: 
    push: #trigger when push happens
        branches:   #trigger when push code into main branch. it can be array, wildcard or single
            - "**"
jobs:   #ki ki kaj hobe seta
    test:     #test the code
        name: Test Machine
        runs-on: ubuntu-latest

        steps: 
            - name: Code checkout on machine
              uses: actions/checkout@v3

            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 24 

            - name: Install Dependencies
              run: npm install

            - name: Run tests
              run: npm run ci:fix

            - name: Build Application
              run: npm run build
    


